### ISSUE TITLE
Federated data preprocessing

### ISSUE THREAD

**Issue by srcansiz** [fedbiomed/fedbiomed#328] opened 2022-08-05 12:30 UTC
In GitLab by @sharkovsky on Aug 5, 2022, 14:30

@ibalelli has implemented an easy method to recover global mean and std, which can the be injected afterwards to standardize clients' dataset with respect to the mean and std of the whole dataset. This can be used as a preliminary step before training a model for data imputation. 

An easy example is provided in this [notebook](https://gitlab.inria.fr/fedbiomed/fedbiomed/-/blob/feature/miwae_adni/notebooks/pytorch-miwae-fedstd-fedprox-breast-cancer.ipynb).

The implementation is currently in [feature/miwae_adni](https://gitlab.inria.fr/fedbiomed/fedbiomed/-/tree/feature/miwae_adni). For the computation of the global means and std she created an aggregator, `FedStandard`, which uses the federated_standardization function defined in functional.py.

When everyone is back from holiday, we should discuss how to integrate this in Fed-BioMed.

**Comment by sharkovsky** [comment] 2023-10-27 11:31
Duplicate of #871

**Closed by sharkovsky** 2023-10-27 11:31 UTC
Labels: candidate
