### ISSUE TITLE
breakpoint displays incorrect round number

### ISSUE THREAD

**Issue by mvesin** [fedbiomed/fedbiomed#833] opened 2023-08-16 08:41 UTC
(thanks to Lucia Innocenti for reporting)

When loading a breakpoint (as in `notebooks/general-breakpoint-save-resume.ipynb`) with:

```
$ loaded_exp = Experiment.load_breakpoint()
```

It seems that the round number is correctly set:
```
$ loaded_exp.info()
...
Rounds already run    2
Rounds total          2
```

But when we run a round from the loaded breakpoint, incorrect round number is displayed (by the `Monitor`) on the researcher (display round 1 instead of round 3). Nevertheless, the correct round number is sent from researcher to node:
```
$ loaded_exp.run(rounds=3, increase=True)
...
2023-08-16 09:36:48,150 fedbiomed INFO - Sending request 
                     To: node_06ca8a52-4872-4235-84ed-2190305f651d 
                     Request: : Perform training with the arguments: {
...
'round': 2,
...
2023-08-16 09:36:48,341 fedbiomed INFO - TRAINING 
                     NODE_ID: node_06ca8a52-4872-4235-84ed-2190305f651d 
                     Round 1 Epoch: 1 | Iteration: 1/100 (1%) | Samples: 48/4800
                      Loss: 0.208707
```

This happens just for the first round after loading the breakpoint (next round correctly displays round 4):
```
2023-08-16 09:36:58,420 fedbiomed INFO - TRAINING 
                     NODE_ID: node_06ca8a52-4872-4235-84ed-2190305f651d 
                     Round 4 Epoch: 1 | Iteration: 1/100 (1%) | Samples: 48/4800
                      Loss: 0.141399 
                     ---------
```

**Comment by sharkovsky** [comment] 2023-08-16 08:46
Hi, this seems a duplicate of #525! 
please close them both after fixing :D

**Comment by mvesin** [comment] 2023-08-16 08:53
thanks @sharkovsky , my bad !

**Closed** 2023-08-16 16:04 UTC
Labels: bug, candidate, done
